data:
  dataset_root: ../kagglehub_cache/datasets/nikhilroxtomar/brain-tumor-segmentation/versions/1
  split_json: data/processed/split_2d.json
  output_dir: models/smp_deeplabv3plus_resnet50_320_seed48_onecycle_aggressive
  image_size: 320
  num_workers: 4

split:
  train_fraction: 0.7
  val_fraction: 0.15

model:
  architecture: smp_deeplabv3plus
  encoder_name: resnet50
  encoder_weights: imagenet
  in_channels: 3
  out_channels: 1

training:
  seed: 48
  epochs: 160
  batch_size: 8
  learning_rate: 0.0001
  weight_decay: 0.00002
  amp: true
  bce_weight: 0.25
  focal_weight: 0.30
  focal_gamma: 2.0
  pos_weight: 2.5
  stronger_aug: true
  aggressive_aug: true
  early_stopping_patience: 36
  scheduler: onecycle
  onecycle_max_lr: 0.00022
  onecycle_pct_start: 0.28
  onecycle_div_factor: 22.0
  onecycle_final_div_factor: 2000.0
  onecycle_anneal_strategy: cos
